# Generated by Django 4.2.7 on 2023-11-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAutos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='marca',
        ),
    ]
