# Generated by Django 4.2.7 on 2023-12-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAutos', '0005_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
